/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mrmathami.View;

import mrmathami.Model.Book;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author C.Anh
 * @author thanhminhmr
 */
public class DemoApp extends javax.swing.JFrame {

    private static final int BOOK_ID = 0;
    private static final int BOOK_NAME = 1;
    private static final int BOOK_AUTHOR = 2;
    private static final int BOOK_PUBLISHER = 3;
    private static final int BOOK_QUANTITY = 4;
    private static final int BOOK_BORROWED = 5;
    private static final int BOOK_OTHERINFO = 6;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnAddLoan;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteBook;
    private javax.swing.JButton btnDeleteLoan;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnModifyBook;
    private javax.swing.JButton btnModifyLoan;
    private javax.swing.JButton btnModifyUser;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRefreshBook;
    private javax.swing.JDialog dlgBook;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOtherInfo;
    private javax.swing.JLabel lblPublisher;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JPanel panelBooks;
    private javax.swing.JPanel panelLoans;
    private javax.swing.JPanel panelUsers;
    private javax.swing.JScrollPane scrollOtherInfo;
    private javax.swing.JScrollPane scrollTblBooks;
    private javax.swing.JScrollPane scrollTblLoans;
    private javax.swing.JScrollPane scrollTblUsers;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTable tblLoans;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtOtherInfo;
    private javax.swing.JTextField txtPublisher;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form DemoApp
     */
    public DemoApp() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DemoApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(DemoApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(DemoApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(DemoApp.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoApp().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgBook = new javax.swing.JDialog();
        lblId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblPublisher = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblOtherInfo = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtPublisher = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        scrollOtherInfo = new javax.swing.JScrollPane();
        txtOtherInfo = new javax.swing.JTextArea();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        panelBooks = new javax.swing.JPanel();
        scrollTblBooks = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        btnDeleteBook = new javax.swing.JButton();
        btnModifyBook = new javax.swing.JButton();
        btnAddBook = new javax.swing.JButton();
        btnRefreshBook = new javax.swing.JButton();
        panelLoans = new javax.swing.JPanel();
        scrollTblLoans = new javax.swing.JScrollPane();
        tblLoans = new javax.swing.JTable();
        btnDeleteLoan = new javax.swing.JButton();
        btnModifyLoan = new javax.swing.JButton();
        btnAddLoan = new javax.swing.JButton();
        panelUsers = new javax.swing.JPanel();
        scrollTblUsers = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnAddUser = new javax.swing.JButton();
        btnModifyUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();

        dlgBook.setSize(new java.awt.Dimension(400, 400));
        dlgBook.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                dlgBookWindowLostFocus(evt);
            }
        });

        lblId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblId.setText("Id:");

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Name:");

        lblAuthor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAuthor.setText("Author:");

        lblPublisher.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPublisher.setText("Publisher:");

        lblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblQuantity.setText("Quantity:");

        lblOtherInfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOtherInfo.setText("Other Infomation:");

        txtId.setEditable(false);

        txtOtherInfo.setColumns(20);
        txtOtherInfo.setRows(5);
        scrollOtherInfo.setViewportView(txtOtherInfo);

        btnOk.setText("OK");
        btnOk.setMaximumSize(new java.awt.Dimension(50, 23));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgBookLayout = new javax.swing.GroupLayout(dlgBook.getContentPane());
        dlgBook.getContentPane().setLayout(dlgBookLayout);
        dlgBookLayout.setHorizontalGroup(
            dlgBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgBookLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(dlgBookLayout.createSequentialGroup()
                        .addGroup(dlgBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblOtherInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(dlgBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(txtId)
                            .addComponent(txtAuthor)
                            .addComponent(txtPublisher)
                            .addComponent(txtQuantity)
                            .addComponent(scrollOtherInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))))
                .addContainerGap())
        );
        dlgBookLayout.setVerticalGroup(
            dlgBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAuthor)
                    .addComponent(lblAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPublisher)
                    .addComponent(lblPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtQuantity)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgBookLayout.createSequentialGroup()
                        .addComponent(lblOtherInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollOtherInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        dlgBookLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAuthor, lblId, lblName, lblOtherInfo, lblPublisher, lblQuantity, txtAuthor, txtId, txtName, txtPublisher, txtQuantity});

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelBooks.setBackground(new java.awt.Color(204, 204, 204));

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Author", "Publisher", "Quantity", "Borrowed Quantity", "Other Information"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBooks.setColumnSelectionAllowed(true);
        tblBooks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblBooks.getTableHeader().setReorderingAllowed(false);
        scrollTblBooks.setViewportView(tblBooks);
        tblBooks.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblBooks.getColumnModel().getColumnCount() > 0) {
            tblBooks.getColumnModel().getColumn(0).setMinWidth(30);
            tblBooks.getColumnModel().getColumn(0).setMaxWidth(60);
            tblBooks.getColumnModel().getColumn(1).setMinWidth(150);
            tblBooks.getColumnModel().getColumn(1).setMaxWidth(600);
            tblBooks.getColumnModel().getColumn(2).setMinWidth(150);
            tblBooks.getColumnModel().getColumn(2).setMaxWidth(600);
            tblBooks.getColumnModel().getColumn(3).setMinWidth(150);
            tblBooks.getColumnModel().getColumn(3).setMaxWidth(600);
            tblBooks.getColumnModel().getColumn(4).setMinWidth(30);
            tblBooks.getColumnModel().getColumn(4).setMaxWidth(60);
            tblBooks.getColumnModel().getColumn(5).setMinWidth(30);
            tblBooks.getColumnModel().getColumn(5).setMaxWidth(60);
            tblBooks.getColumnModel().getColumn(6).setMinWidth(150);
            tblBooks.getColumnModel().getColumn(6).setMaxWidth(1200);
        }

        btnDeleteBook.setText("Delete");
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });

        btnModifyBook.setText("Modify");
        btnModifyBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyBookActionPerformed(evt);
            }
        });

        btnAddBook.setText("Add");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        btnRefreshBook.setText("Refresh");
        btnRefreshBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBooksLayout = new javax.swing.GroupLayout(panelBooks);
        panelBooks.setLayout(panelBooksLayout);
        panelBooksLayout.setHorizontalGroup(
            panelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTblBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBooksLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefreshBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifyBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteBook)))
                .addContainerGap())
        );

        panelBooksLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddBook, btnDeleteBook, btnModifyBook, btnRefreshBook});

        panelBooksLayout.setVerticalGroup(
            panelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTblBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteBook)
                    .addComponent(btnModifyBook)
                    .addComponent(btnAddBook)
                    .addComponent(btnRefreshBook))
                .addContainerGap())
        );

        tabbedPane.addTab("Books", panelBooks);

        panelLoans.setBackground(new java.awt.Color(204, 204, 204));

        tblLoans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "BookID", "Book", "Username", "Borrow Date", "Due Date", "Other Information"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoans.setColumnSelectionAllowed(true);
        tblLoans.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblLoans.getTableHeader().setReorderingAllowed(false);
        scrollTblLoans.setViewportView(tblLoans);
        tblLoans.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblLoans.getColumnModel().getColumnCount() > 0) {
            tblLoans.getColumnModel().getColumn(0).setMinWidth(30);
            tblLoans.getColumnModel().getColumn(0).setMaxWidth(60);
            tblLoans.getColumnModel().getColumn(1).setMinWidth(150);
            tblLoans.getColumnModel().getColumn(1).setMaxWidth(600);
            tblLoans.getColumnModel().getColumn(2).setMinWidth(100);
            tblLoans.getColumnModel().getColumn(2).setMaxWidth(200);
            tblLoans.getColumnModel().getColumn(3).setMinWidth(150);
            tblLoans.getColumnModel().getColumn(3).setMaxWidth(600);
            tblLoans.getColumnModel().getColumn(4).setMinWidth(100);
            tblLoans.getColumnModel().getColumn(4).setMaxWidth(200);
            tblLoans.getColumnModel().getColumn(5).setMinWidth(100);
            tblLoans.getColumnModel().getColumn(5).setMaxWidth(200);
            tblLoans.getColumnModel().getColumn(6).setMinWidth(150);
            tblLoans.getColumnModel().getColumn(6).setMaxWidth(1200);
        }

        btnDeleteLoan.setText("Delete");
        btnDeleteLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLoanActionPerformed(evt);
            }
        });

        btnModifyLoan.setText("Modify");

        btnAddLoan.setText("Add");
        btnAddLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoansLayout = new javax.swing.GroupLayout(panelLoans);
        panelLoans.setLayout(panelLoansLayout);
        panelLoansLayout.setHorizontalGroup(
            panelLoansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoansLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTblLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoansLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddLoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifyLoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteLoan)))
                .addContainerGap())
        );

        panelLoansLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddLoan, btnDeleteLoan, btnModifyLoan});

        panelLoansLayout.setVerticalGroup(
            panelLoansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoansLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTblLoans, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLoansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteLoan)
                    .addComponent(btnModifyLoan)
                    .addComponent(btnAddLoan))
                .addContainerGap())
        );

        tabbedPane.addTab("Loans", panelLoans);

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Role", "Full Name", "Birth Date", "Gender", "Other Information"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsers.getTableHeader().setReorderingAllowed(false);
        scrollTblUsers.setViewportView(tblUsers);
        tblUsers.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblUsers.getColumnModel().getColumnCount() > 0) {
            tblUsers.getColumnModel().getColumn(0).setMinWidth(30);
            tblUsers.getColumnModel().getColumn(0).setMaxWidth(60);
            tblUsers.getColumnModel().getColumn(1).setMinWidth(150);
            tblUsers.getColumnModel().getColumn(1).setMaxWidth(600);
            tblUsers.getColumnModel().getColumn(2).setMinWidth(100);
            tblUsers.getColumnModel().getColumn(2).setMaxWidth(200);
            tblUsers.getColumnModel().getColumn(3).setMinWidth(150);
            tblUsers.getColumnModel().getColumn(3).setMaxWidth(600);
            tblUsers.getColumnModel().getColumn(4).setMinWidth(100);
            tblUsers.getColumnModel().getColumn(4).setMaxWidth(200);
            tblUsers.getColumnModel().getColumn(5).setMinWidth(100);
            tblUsers.getColumnModel().getColumn(5).setMaxWidth(200);
            tblUsers.getColumnModel().getColumn(6).setMinWidth(150);
            tblUsers.getColumnModel().getColumn(6).setMaxWidth(1200);
        }

        btnAddUser.setText("Add");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnModifyUser.setText("Modify");

        btnDeleteUser.setText("Delete");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsersLayout = new javax.swing.GroupLayout(panelUsers);
        panelUsers.setLayout(panelUsersLayout);
        panelUsersLayout.setHorizontalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTblUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsersLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifyUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteUser)))
                .addContainerGap())
        );

        panelUsersLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddUser, btnDeleteUser, btnModifyUser});

        panelUsersLayout.setVerticalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTblUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteUser)
                    .addComponent(btnModifyUser)
                    .addComponent(btnAddUser))
                .addContainerGap())
        );

        tabbedPane.addTab("Users", panelUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtId.getText())) {
            if (Book.createBook(txtName.getText(), txtAuthor.getText(), txtPublisher.getText(), Integer.parseInt(txtQuantity.getText()), txtOtherInfo.getText())) {
                btnRefreshBookActionPerformed(evt);
                JOptionPane.showMessageDialog(rootPane, "Done create Book", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error create Book", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (Book.updateBook(Integer.parseInt(txtId.getText()), txtName.getText(), txtAuthor.getText(), txtPublisher.getText(), Integer.parseInt(txtQuantity.getText()), txtOtherInfo.getText())) {
                btnRefreshBookActionPerformed(evt);
                JOptionPane.showMessageDialog(rootPane, "Done update Book", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error update Book", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        dlgBook.setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dlgBook.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookActionPerformed
        int selectedRow = tblBooks.getSelectedRow();
        if (selectedRow >= 0) {
            String name = (String) tblBooks.getValueAt(selectedRow, BOOK_NAME);
            if (JOptionPane.showConfirmDialog(rootPane, "Do you want do delete this Book?\n" + name,
                    "Confirm delete", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                if (Book.deleteBook((Integer) tblBooks.getValueAt(selectedRow, BOOK_ID))) {
                    btnRefreshBookActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error delete Book", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteBookActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        // TODO add your handling code here:
        txtId.setText("");
        dlgBook.setVisible(true);
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnDeleteLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteLoanActionPerformed

    private void btnAddLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddLoanActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnRefreshBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshBookActionPerformed
        // clean the table, put new data
        DefaultTableModel model = (DefaultTableModel) tblBooks.getModel();
        model.setRowCount(0);
        Book.getBookList().forEach(book -> {
            model.addRow(new Object[]{book.id, book.name, book.author, book.publisher, book.quantity, book.borrowed, book.otherInfo});
        });
    }//GEN-LAST:event_btnRefreshBookActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnRefreshBookActionPerformed(null);
    }//GEN-LAST:event_formWindowOpened

    private void dlgBookWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgBookWindowLostFocus
        // TODO add your handling code here:
        dlgBook.setVisible(false);
    }//GEN-LAST:event_dlgBookWindowLostFocus

    private void btnModifyBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyBookActionPerformed
        // TODO add your handling code here:
        int row = tblBooks.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblBooks.getModel();
        txtId.setText(model.getValueAt(row, BOOK_ID).toString());
        dlgBook.setVisible(true);
        
    }//GEN-LAST:event_btnModifyBookActionPerformed
}
